package pedrozc90

import java.nio.file.FileSystems

import sbt.Keys._
import sbt._
import sbt.plugins.JvmPlugin

object QueryDSLPlugin extends AutoPlugin {

    override def requires = JvmPlugin

    val QueryDSL = config("querydsl").hide

    object autoImport {
        val queryDSLVersion = SettingKey[String]("querydsl-version", "QueryDSL version.")
        val queryDSLPackage = SettingKey[String]("querydsl-package", "QueryDSL package to scan.")
        val queryDSLIncludes = SettingKey[Seq[String]](
            "querydsl-includes",
            "Globs, relative to the scanned package, of sources to process. Empty processes all."
        )
        val queryDSLProcessor = SettingKey[String]("querydsl-processor", "QueryDSL annotation processor class.")
        val queryDSLOptions = SettingKey[Seq[String]]("querydsl-options", "Extra javac options, e.g. -Aquerydsl.*.")
        val queryDSLGenerate =
            TaskKey[Seq[File]]("queryDSLGenerate", "Generates QueryDSL Q* sources without compiling.")
    }

    import autoImport._

    override def projectConfigurations: Seq[Configuration] = Seq(QueryDSL)

    override def projectSettings: Seq[Setting[_]] = Seq(
        queryDSLVersion := "4.4.0",
        queryDSLPackage := "models",
        queryDSLIncludes := Seq.empty,
        queryDSLProcessor := coordinates((queryDSLVersion in QueryDSL).value)._2,
        queryDSLOptions := Seq.empty,
        libraryDependencies ++= {
            val version = (queryDSLVersion in QueryDSL).value
            val (organization, _) = coordinates(version)
            Seq(
                organization % "querydsl-apt" % version % QueryDSL.name,
                organization % "querydsl-jpa" % version
            )
        },
        managedClasspath in QueryDSL := Classpaths.managedJars(QueryDSL, classpathTypes.value, update.value),
        queryDSLGenerate := generateQueryTypes.value,
        sourceGenerators in Compile += queryDSLGenerate.taskValue
    )

    // QueryDSL 3.x lives under com.mysema.querydsl / com.mysema.query, 4.x under com.querydsl
    private def coordinates(version: String): (String, String) =
        if (version.startsWith("3.")) ("com.mysema.querydsl", "com.mysema.query.apt.jpa.JPAAnnotationProcessor")
        else ("com.querydsl", "com.querydsl.apt.jpa.JPAAnnotationProcessor")

    private def matchers(globs: Seq[String]) = globs.map(g => FileSystems.getDefault.getPathMatcher("glob:" + g))

    // runs only the QueryDSL processor over the matched sources and returns the generated sources
    private def generateQueryTypes = Def.task {
        val version = (queryDSLVersion in QueryDSL).value
        val processor = queryDSLProcessor.value
        val includes = queryDSLIncludes.value
        val sourceDir = (sourceDirectory in Compile).value
        val root = sourceDir / queryDSLPackage.value
        val included = matchers(includes)
        val sources = (root ** "*.java").get.filter { f =>
            val path = root.toPath.relativize(f.toPath)
            included.isEmpty || included.exists(_.matches(path))
        }.toSet
        val outputDirectory = (sourceManaged in Compile).value / "querydsl"
        val classpath = ((dependencyClasspath in Compile).value ++ (managedClasspath in QueryDSL).value).map(_.data)
        val javac = (compilers in Compile).value.javac
        val log = streams.value.log
        // -sourcepath resolves types outside the matched sources without making them processor roots
        val options = Seq(
            "-proc:only",
            "-processor",
            processor,
            "-s",
            outputDirectory.getAbsolutePath,
            "-sourcepath",
            sourceDir.getAbsolutePath,
            "-implicit:none"
        ) ++ queryDSLOptions.value
        // the cache only tracks sources, so settings changes must land in a new cache directory
        val key = (version +: options ++: includes).hashCode.toHexString

        val generate = FileFunction.cached(
            streams.value.cacheDirectory / s"querydsl-$key",
            FilesInfo.lastModified,
            FilesInfo.exists
        ) { in: Set[File] =>
            // drop sources generated by a previous run, possibly for other settings
            IO.delete(outputDirectory)
            outputDirectory.mkdirs()
            log.debug(s"QueryDSL: processing ${in.size} sources: " + in.map(_.getPath).mkString(", "))
            try {
                javac(in.toSeq, classpath, outputDirectory, options)(log)
            } catch {
                // rethrow so the failed run is not cached and the next compile retries
                case e: sbt.compiler.CompileFailed =>
                    log.error("QueryDSL: generation failed")
                    throw e
            }
            (outputDirectory ** "*.java").get.toSet
        }

        generate(sources).toSeq.map(_.getAbsoluteFile)
    }
}
