application {
    secret = "changeme-sample-secret-not-for-production"
    langs = "en"
}

# in-memory H2, recreated on every start
db {
    default {
        jndiName = DefaultDS
        driver = org.h2.Driver
        url = "jdbc:h2:mem:play"
    }
}

jpa {
    default = defaultPersistenceUnit
}

logger {
    root = ERROR
    play = INFO
    application = DEBUG
}
